### ISSUE TITLE
HTML markup error in v12/en/tutorials_data.json

### ISSUE THREAD

**Issue by AnimatIan** [ot4i/ace-tutorials#5] opened 2021-06-02 16:46 UTC
In https://github.com/ot4i/ace-tutorials/blob/gh-pages/v12/en/tutorials_data.json there is at least one HTML markup error that affects presentation of the tutorials data outside the Toolkit (in IBM Docs)

```
                "section": "<b>Prepare a server to host the Web UI for administering an Integration Server</b>",
                "steps": {
                  "type": "ordered",
                  "details": [
                    {
                      "details": "Open an App Connect Enterprise Command Console and create a working directory by running the mqsicreateworkdir command:<br><ul><li>If you are using a Windows platform: <code>mqsicreateworkdir C:\\MyServer</code></li><li>If you are using a UNIX platform: <code>mqsicreateworkdir /home/exampleuser/MyServer</li></ul>"
```

Please add a closing `</code>` before the `</li>`

**Comment by AnimatIan** [comment] 2021-06-02 18:35
Another HTML markup fix; please complete the "</b>" in "section"

```
"run": {
          "overview": {
            "name": "Run",
            "heading": "Exercise the administrative REST API",
            "_runComment": "The full steps for the user to run through the tutorial. Use 'sections' to render paragraphs, 'steps' with a type of 'ordered' or 'unordered' to render HTML lists, and 'substeps' to render nested lists.",
            "sections": [
              {
                "section": "<b>Interact with the Integration Server:</b",
```

**Comment by bthomps** [comment] 2021-06-03 08:27
The root cause of the first issue is fixed in https://github.com/ot4i/webui-tutorial/commit/3b5b8ec5f3b45ce92dfe9e7dc2b238d25ee61de9

The root cause of the second issue is fixed in https://github.com/ot4i/adminrestapi-tutorial/commit/bfe33b6fa987ffedfae611f597992b9fb7ca7fc8

The actual json file (tutorials_data.json) is re-created when I run a build process for the tutorials. The process sucks down the repo_metadata.json for all the current tutorials and compiles together a single json file, which is then used by the Toolkit for displaying the overview previews. It doesnt take me long to run the rebuild and checkin the results (about 15mins), but if there are several problems in the document, they could stem from different tutorials. For example, the first issue you highlight is actually in the tutorial `Getting started - Exploring the Web UI` and the second one you highlight is in `Getting started - Exploring the Admin REST API` .  There is an economy of scale for me to put as many of these right at the same time as possible. For example, before rebuilding, I may go through and expunge references to "IBM Knowledge Center" so will probably rebuild the changes in a few hours ... meanwhile please ping me directly if you see this update before then and we can discuss.

**Comment by bthomps** [comment] 2021-06-04 13:24
Rebuild has now occurred as part of https://github.com/ot4i/ace-tutorials/commit/d527b630498ef1d7b407498b0e1a669d9531ac50
Issue can now be closed.

**Closed as completed by bthomps** 2021-06-04 13:24 UTC
